version: '3.9'

services:
  book-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - book-api-network

  book-api-db:
    image: postgres
    restart: always
    env_file:
      - src/env/.docker-compose.env
    ports:
      - 5432:5432
    volumes:
      - book-api-db:/var/lib/postgresql/data
    networks:
      - book-api-network
  
  book-api-db-gui:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - book-api-db
    networks:
      - book-api-network

volumes:
  book-api-db:

networks:
  book-api-network:
    driver: bridge