version: '3.9'

services:
  book-api-db:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - book-api-db:/var/lib/postgresql/data
    networks:
      - book-api-network

  book-api-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8888:80
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    volumes:
      - book-api-admin:/var/lib/pgadmin
    depends_on:
      - book-api-db

volumes:
  book-api-db:
  book-api-admin:

networks:
  book-api-network:
    driver: bridge